for i, _ in enumerate(__import__("sys").argv[1]): print("".join(list(__import__("sys").argv[1].upper())[i:]+list(__import__("sys").argv[1].upper())[:i]))

'''
Prints a word tile for the given word.
PS C:\dev\personal> python .\letter_tile.py "Cerner two to the fifth "
CERNER TWO TO THE FIFTH 
ERNER TWO TO THE FIFTH C
RNER TWO TO THE FIFTH CE
NER TWO TO THE FIFTH CER
ER TWO TO THE FIFTH CERN
R TWO TO THE FIFTH CERNE
 TWO TO THE FIFTH CERNER
TWO TO THE FIFTH CERNER
WO TO THE FIFTH CERNER T
O TO THE FIFTH CERNER TW
 TO THE FIFTH CERNER TWO
TO THE FIFTH CERNER TWO
O THE FIFTH CERNER TWO T
 THE FIFTH CERNER TWO TO
THE FIFTH CERNER TWO TO
HE FIFTH CERNER TWO TO T
E FIFTH CERNER TWO TO TH
 FIFTH CERNER TWO TO THE
FIFTH CERNER TWO TO THE
IFTH CERNER TWO TO THE F
FTH CERNER TWO TO THE FI
TH CERNER TWO TO THE FIF
H CERNER TWO TO THE FIFT
 CERNER TWO TO THE FIFTH
'''